kedacore/charts

keda/crds/keda.k8s.io_scaledobjects_crd.yaml, keda/crds/keda.k8s.io_triggerauthentications_crd.yaml
resolves https://github.com/kedacore/keda/issues/406
This is a backwards compat way so both helm 2 and helm 3 will work with chart install
=> helm 3 crd support

.github/CODEOWNERS
=> Add @zroubalik to CODEOWNERS

keda/Chart.yaml
KEDA is not only for Azure Functions
=> KEDA is not only for Azure Functions

keda/Notes.txt, keda/README.md, keda/templates/01-serviceaccount.yaml, keda/templates/10-keda-clusterrole.yaml, keda/templates/11-keda-clusterrolebinding.yaml, keda/templates/12-keda-deployment.yaml, keda/templates/13-keda-poddisruptionbudget.yaml, keda/templates/20-metrics-clusterrole.yaml, keda/templates/21-metrics-clusterrolebinding.yaml, keda/templates/22-metrics-deployment.yaml, keda/templates/23-metrics-service.yaml, keda/templates/24-metrics-apiservice.yaml, keda/templates/25-metrics-poddisruptionbudget.yaml, keda/values.yaml
Document & reshuffle Helm chart variables to be more consistent and easier to discover in tools like [Helm Hub](https://hub.helm.sh/charts/kedacore/keda) & [Artifact Hub](https://artifacthub.io/packages/olm/community-operators/keda).
Closes #19
=> Document & reshuffle Helm chart variables

keda/README.md, keda/templates/22-metrics-deployment.yaml, keda/values.yaml
Signed-off-by: Chaitanya Kuduvalli Ramachandra <chaitanya.r@ETC02Y77ZVJG5H.local>
Relates to https://github.com/kedacore/keda/issues/1105
=> Changing docker image name from adapter to apiserver

keda/templates/10-keda-clusterrole.yaml
Fixes: #71 
Cluster role was changed on many places in v2, bringing these changes to charts as well.
=> making cluster role up to date

.github/workflows/ci.yml
=> Remove Helm 2.x deploy

.github/workflows/ci.yml
=> List KEDA resources to ensure CLI works

.github/workflows/ci.yml
Signed-off-by: Tom Kerkhove kerkhove.tom@gmail.com
=> Remove linting for Helm 2.x

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Provide PR template

keda/values.yaml
Migrate to our containers on GitHub Container Registry from https://github.com/orgs/kedacore/packages?type=source
Fixes https://github.com/kedacore/charts/issues/127
Relates to https://github.com/kedacore/governance/issues/16
=> feat: Migrate to our containers on GitHub Container Registry

keda/values.yaml
=> fixing ghcr.io repo link

keda/README.md
- ~[ ] A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*~
Fixes #
=> Update README with new images

keda/crds/scaledjobs.keda.sh.yaml
The ScaledJob CRD wasn't synced with last updates on the core
=> Fixing ScaledJob CRD

keda/Chart.yaml, keda/README.md, keda/templates/15-keda-prometheusrules.yaml, keda/values.yaml
=> Add PrometheusRules support for keda operator

keda/Chart.yaml, keda/templates/15-keda-prometheusrules.yaml
=> Fix typo: Change prometheusRule --> PrometheusRule for Kind

keda/templates/02-crd-clustertriggerauthentications.yaml, keda/templates/05-crd-triggerauthentications.keda.sh.yaml
Signed-off-by: Shubham Kuchhal <shubham.kuchhal@india.nec.com>
Update the CRDs according to [kedacore/keda#1862](https://github.com/kedacore/keda/pull/1862)
ref: [#1826](https://github.com/kedacore/keda/issues/1826)
=> Update CRDs: TriggerAuthentication and ClusterTriggerAuthentication

keda/README.md, keda/templates/22-metrics-deployment.yaml, keda/values.yaml
…erences services by local name
Fixes #
=> feat: Provide capability to configure dns policy

keda/values.yaml
Fix typo on `values.yaml`file in Helm chart.
Fixes #
Typo on `values.yaml`file in Helm chart.
Signed-off-by: David de Torres <maellyssa@gmail.com>
=> Fix typo in values.yaml

keda/templates/10-keda-clusterrole.yaml, keda/templates/12-keda-deployment.yaml
=> Reflect changes with migration to Kubebuilder v3

http-add-on/Chart.yaml, http-add-on/README.md, http-add-on/templates/_helpers.tpl, http-add-on/templates/deployment.yaml, http-add-on/templates/rbac.yml, http-add-on/templates/svc.yaml, http-add-on/values.yaml, keda/Chart.yaml, keda/README.md, keda/templates/01-serviceaccount.yaml, keda/templates/02-crd-clustertriggerauthentications.yaml, keda/templates/03-crd-scaledjobs.keda.sh.yaml, keda/templates/04-crd-scaledobjects.keda.sh.yaml, keda/templates/05-crd-triggerauthentications.keda.sh.yaml, keda/templates/10-keda-clusterrole.yaml, keda/templates/11-keda-clusterrolebinding.yaml, keda/templates/12-keda-deployment.yaml, keda/templates/13-keda-poddisruptionbudget.yaml, keda/templates/14-keda-podmonitor.yaml, keda/templates/15-keda-prometheusrules.yaml, keda/templates/20-metrics-clusterrole.yaml, keda/templates/21-metrics-clusterrolebinding.yaml, keda/templates/22-metrics-deployment.yaml, keda/templates/23-metrics-service.yaml, keda/templates/24-metrics-apiservice.yaml, keda/templates/25-metrics-poddisruptionbudget.yaml, keda/templates/26-metrics-podmonitor.yaml, keda/templates/_helpers.tpl, keda/values.yaml
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>
Fixes #
=> Support for custom labels

CONTRIBUTING.md, keda/Chart.yaml
Signed-off-by: Jorge Turrado <jorge.turrado@docplanner.com>
Fixes #
=> Add myself to chart maintaners and small nits in release process

CONTRIBUTING.md
Provide guidance on milestones & release notes for shipping newer version so that:
- We add all Helm chart changes from the milestone
- Create a dedicated milestone for the shipped version
- We just refer to the core release notes instead of listing them all here
=> docs: Provide guidance on milestones & release notes for shipping newer version

http-add-on/README.md, http-add-on/templates/deployment-operator.yaml, http-add-on/values.yaml
Referenced the value of kube-rbac-proxy image and tag from values.yml file.
Fixes #207
=> Add kube-rbac-proxy image to values.yaml images list

docs/artifacthub-repo.yml
Become verified publisher on Artifact Hub for our Helm chart.
=> feat: Become verified publisher on Artifact Hub

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci-core.yml, .github/workflows/ci-external-scaler-azure-cosmos-db.yml, .github/workflows/ci-http-add-on.yml, .vscode/settings.json, CONTRIBUTING.md, docs/index.yaml, keda/Chart.yaml, keda/README.md
Prepare for `master` to `main` migration so we can rename the branch.
Relates to #195
=> chore: Prepare for `master` to `main` migration

.github/workflows/ci-core.yml, .github/workflows/ci-external-scaler-azure-cosmos-db.yml, .github/workflows/ci-http-add-on.yml
List all used Kubernetes versions in matric (CI)
=> chore: List all used Kubernetes versions in matric (CI)

external-scaler-azure-cosmos-db/Chart.yaml, http-add-on/Chart.yaml, keda/Chart.yaml
Specify supported Kubernetes versions which is in line with our automated CI testing and KEDA core needs.
Fixes https://github.com/kedacore/charts/issues/241
=> chore: Specify supported Kubernetes versions

keda/templates/12-keda-deployment.yaml, keda/templates/22-metrics-deployment.yaml
Provide node selector for KEDA Core since we require Linux.
Fixes #200
=> feat: Provide node selector for KEDA Core

keda/values.yaml
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
Relates: https://github.com/kedacore/keda/issues/3012
=> Don't hardcode UIDs in securityContext

keda/README.md, keda/templates/12-keda-deployment.yaml, keda/templates/22-metrics-deployment.yaml, keda/values.yaml
=> fix: revert wrong changes in security context

http-add-on/README.md, keda/README.md
=> Fix README.md

keda/templates/01-serviceaccount.yaml
Signed-off-by: Vighnesh Shenoy <vighneshq@gmail.com>
Fixes #284
=> Make ClientId and TenantId optional when using Workload Identity.

http-add-on/Chart.yaml, http-add-on/README.md, http-add-on/templates/deployment-interceptor.yaml, http-add-on/templates/deployment-operator.yaml, http-add-on/templates/deployment-scaler.yaml, http-add-on/values.yaml
* Added the option to specify imagePullSecrets
=> feat: Provide support for image pull secret in HTTP add-on

CONTRIBUTING.md
Related to https://github.com/kedacore/keda-docs/pull/926
=> fix: Update release template to use correct commands

.github/workflows/ci-core.yml, keda/Chart.yaml
Related to https://github.com/kedacore/keda/pull/3606/
=> chore(keda): update k8s min version according to our support policy

.github/PULL_REQUEST_TEMPLATE.md
Deprecations & breaking changes policy introduction
Relates to https://github.com/kedacore/governance/issues/68
=> chore(contributing): Deprecations & breaking changes policy introduction

keda/templates/10-keda-clusterrole.yaml, keda/templates/14-keda-deployment.yaml, keda/templates/22-metrics-deployment.yaml
Related to https://github.com/kedacore/charts/pull/352
=> fix KEDA CI checks

CONTRIBUTING.md
=> chore: add the version to release template

.github/workflows/ci-http-add-on.yml, http-add-on/Chart.yaml
=> chore(http-add-on): support same k8s versions as KEDA

http-add-on/README.md
=> fix(http-add-on): update wrong references

.github/workflows/ci-core.yml
=> fix: Use proper stage names

keda/values.yaml
=> chore: remove comment about removing the option to disable webhooks

CONTRIBUTING.md, keda/.helmignore, keda/README.md, keda/README.md.gotmpl, keda/values.yaml
=> docs(keda): Introduce helm-docs for documentation

http-add-on/templates/deployment-scaler.yaml, http-add-on/templates/scaledobject-interceptor.yaml
Updates HTTP Add-On chart with the new scaling configuration for the Interceptor.
Depends-on: kedacore/http-add-on#720
Fixes: kedacore/http-add-on#718
=> HTTP Add-On: new interceptor scaling configuration

keda/templates/webhooks/deployment.yaml
=> fix: fix hostNetwork for webhooks

README.md, http-add-on/README.md, http-add-on/README.md.gotmpl, keda/README.md, keda/README.md.gotmpl
KEDA is a CNCF Graduated project
Relates to https://github.com/kedacore/governance/issues/63
=> chore: KEDA is a CNCF Graduated project

.github/workflows/ci-core.yml, .github/workflows/ci-http-add-on.yml
=> chore: update k8s versions for testing the charts

.github/workflows/ci-core.yml
=> chore: remove whitespaces

keda/templates/manager/deployment.yaml
Relates: https://github.com/kedacore/keda/issues/4861
=> feat: configurable K8s cluster domain for Cert Manager

.github/workflows/ci-core.yml, .github/workflows/ci-external-scaler-azure-cosmos-db.yml, .github/workflows/ci-http-add-on.yml
=> chore: Improve the CI on PRs to be more efficient

http-add-on/README.md, http-add-on/templates/scaler/deployment.yaml, http-add-on/values.yaml
=> feat(add-on): Supporting streamInterval configuration

README.md
=> chore: update versions in README.md

keda/templates/manager/deployment.yaml
=> fix: Declare missing port in KEDA operator

keda/templates/cert-manager/self-ca.yaml
=> fix: Don't recreate CA with 8 months until it expires

.github/workflows/ci-core.yml, .github/workflows/ci-http-add-on.yml, http-add-on/README.md, http-add-on/templates/crd.yaml, http-add-on/templates/interceptor/deployment.yaml, http-add-on/templates/interceptor/rbac.yml, http-add-on/templates/interceptor/service-admin.yaml, http-add-on/templates/interceptor/service-proxy.yaml, http-add-on/templates/operator/service.yaml, http-add-on/templates/scaler/deployment.yaml, http-add-on/templates/scaler/rbac.yml, http-add-on/templates/scaler/service.yaml, http-add-on/values.yaml
=> chore(add-on): Apply HTTP Add-on changes on Helm chart

keda/templates/metrics-server/service.yaml
Fixes #648
respect service.type.
=> respect service.type

keda/values.yaml
=> chore(keda): Remove outdated comment

keda/templates/crds/crd-cloudeventsources.yaml
Update cloudeventsource with scaledjob event type
Fixes #https://github.com/kedacore/keda/issues/3523
=> Update cloudeventsource with scaledjob event type

keda/templates/crds/crd-cloudeventsources.yaml, keda/templates/crds/crd-clustercloudeventsources.yaml, keda/templates/crds/crd-clustertriggerauthentications.yaml, keda/templates/crds/crd-scaledjobs.yaml, keda/templates/crds/crd-scaledobjects.yaml, keda/templates/crds/crd-triggerauthentications.yaml
Fixes https://github.com/kedacore/charts/issues/733
=> KEDA: sync CRDs with the core

.github/workflows/ci-core.yml, .github/workflows/ci-http-add-on.yml
=> chore: update actions and kubernetes versions in CI workflows

keda/Chart.yaml, keda/README.md, keda/templates/manager/deployment.yaml, keda/values.yaml
I have added the hostAliases to keda-operator helm template
Fixes #
=> Adding hostAliases to keda-operator deployment helm template
