kedacore/charts

- .github/workflows/lint-helm-charts.yml
Provide GitHub Action to lint Helm charts for 3.x & 2.x.
Example: https://github.com/tomkerkhove/charts-1/pull/2
> Provide GitHub Action to lint Helm charts for 3.x & 2.x

- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
* enables us to modify log level for Metrics Server
* documents possible log levels for both Operator and Metrics server
Related issue: https://github.com/kedacore/keda/issues/618
> logging levels for Operator and Metrics Server

- keda/templates/12-keda-deployment.yaml
- keda/values.yaml
When creating networkPolicies across namespaces, it's useful to assign labels to the keda operator (the example here being that in the postgreSQL-scaler, we need to access a postgres service in a separate namespace).
> add option for users to insert labels on KEDA operator deployment

- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
> Provide capability to specify annotations in Helm chart

- keda/Chart.yaml
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Add the ability to define `priorityClassName` for KEDA and Metrics Adapter pods in `values.yaml`.
> Add priorityClassName to pods specs

- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
After discussions in https://github.com/kedacore/charts/issues/35 and https://github.com/kedacore/keda/issues/706, this moves the podAnnotations to the correct place in deployment.spec.template
> Move podAnnotations to deployment specs

- keda/templates/12-keda-deployment.yaml
Adding label as proposed in https://github.com/kedacore/keda/pull/745
> Label for operator-sdk metrics service selection

- keda/Chart.yaml
- keda/templates/12-keda-deployment.yaml
- keda/values.yaml
This allows for adjusting the `zap-time-encoding` argument to the KEDA Operator so that time formats like ISO8601 can be used. ISO8601 is more reader-friendly when examining the timestamps in the logs and possibly could be used as the default value in the values.yaml.
> Adding the logTimeFormat value for time formatting in the KEDA Operator

- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Remove instance count for KEDA workloads as we only support single-instance deployments.
Relates to #50
> Remove instance count for KEDA workloads

- keda/Chart.yaml
- keda/templates/12-keda-deployment.yaml
I've faced an issue with setting up kiam podAnnotation for keda deployment.
Got the following error:
```
Error: template: keda/templates/12-keda-deployment.yaml:30:21: executing "keda/templates/12-keda-deployment.yaml" at <.Values.podAnnotations.keda>: wrong type for value; expected string; got map[string]interface {}
```
For metricsAdapter everything worked as expected.
So replacing `tpl` function with `toYaml` must resolve the issue.
> Fix podAnnotations for keda deployment

- keda/templates/01-serviceaccount.yaml
- keda/values.yaml
Currently, the chart supports pod annotations which enables the kiam/kube2iam case. This adds the option of a serviceaccount annotation which enables the EKS service account IAM roles case, so that `identityOwner: operator` can be used successfully with EKS.
> Add serviceAccount.annotations to enable EKS IAM roles

- keda/crds/scaledjobs.keda.sh.yaml
Use patched version of ScaledJob CRD.
Follow-up of https://github.com/kedacore/charts/pull/60.
> Use patched version of ScaledJob CRD

- keda/values.yaml
The tags in the `values.yaml` were still those for the beta release. This PR updates the tags to be those of the RC release.
Signed-off-by: Maxence Boutet <mboutet@explorance.com>
> Update images' tag (from beta to rc)

- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
```shell
tkerkhove@CLT-TKERKHOVE  C:\Code\GitHub\keda-charts   default-tag ↑1                                                                                                                                [07:17]
❯ helm template keda
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: keda-operator
namespace: platform-gateway-firmware-repository-dev
labels:
<redacted>
spec:
replicas: 1
selector:
matchLabels:
app: keda-operator
template:
metadata:
labels:
app: keda-operator
spec:
serviceAccountName: keda-operator
securityContext: …
```
> Use Helm charts's app version as default tag

- keda/Chart.yaml
Fixes issue with argocd unable to install KEDA as argocd by default uses helm2 when `apiVersion` is set to `v1` in the `Chart.yaml`
Changes
Changed `apiVersion` to `v2` in `Chart.yaml` to automatically default argocd to use helm3 when installing the chart
References
https://argoproj.github.io/argo-cd/user-guide/helm/#helm-version
> Change Helm Chart API version to v2

- keda/README.md
- keda/templates/23-metrics-service.yaml
- keda/values.yaml
Adding the ability to add annotations to the service. This can be used for things like ArgoCD to guarantee order of installation to ensure the service exists before the APIService
> Adding the ability to add annotations to service

- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
Improvement for https://github.com/kedacore/keda/issues/1377
**Without:**
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: keda-operator
namespace: platform-gateway-g3-dev
labels:
app: keda-operator
name: keda-operator
<redacted>
spec:
replicas: 1
selector:
matchLabels:
app: keda-operator
template:
metadata:
labels:
app: keda-operator
spec:
serviceAccountName: keda-operator
securityContext:
{}
containers:
- name: keda-operator
securityContext:
{}
image: "docker.io/kedacore/keda:2.0.0"
<redacted>
env:
- name: WATCH_NAMESPACE
value: ""
- name: POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: OPERATOR_NAME
value: keda-operator
volumeMounts:
resources:
{}
volumes:
---
apiVersion: apps/v1
kind: Deployment
metadata: …
```
> Provide better documentation on watching namespaces

- keda/templates/10-keda-clusterrole.yaml
Allow the operator to read serviceaccounts.
This is required for the [aws-eks pod identity provider](https://keda.sh/docs/2.0/concepts/authentication/#eks-pod-identity-webhook-for-aws) to work. IAM roles are bound to serviceAccounts (using an annotation), and so the operator needs to be able to read the relevant serviceAccount in order to discover which role it should assume.
> Allow read/list/get of serviceaccounts

- keda/templates/10-keda-clusterrole.yaml
I am getting error after helm upgrade
```
E0128 02:33:19.968637       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:keda:keda-operator" cannot list resource "deployments" in API group "apps" at the cluster scope
```
https://github.com/kedacore/keda/blob/f11984582ca412d0de526b0e4022b1d268e02d56/config/rbac/role.yaml#L40-L47
https://github.com/kedacore/keda/commit/f3b34d902a6ec62f1563bed5d86a134d8260a0c9
> Allow list/watch of deployments and statefullset

- keda/templates/21-metrics-clusterrolebinding.yaml
- keda/values.yaml
This PR resolves some linting issues I noticed after running `ct lint --validate-maintainers=false --charts=keda/` (https://github.com/helm/chart-testing)
> Fix some linting issues

- keda/README.md
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Signed-off-by: Matthew Ingle <mringle94@gmail.com>
This pull request adds a configuration option for the keda metrics server to use host network. In environments such as EKS this is important as the masters are unable to communicate with the pods directly in the CNI. (Similar to this issue with the ELK operator https://github.com/elastic/cloud-on-k8s/issues/1369)
By default hostnetwork is disable this simply enables operators to flip it on if needed.
> feat: added ability to enable host network for keda metrics server

- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/values.yaml
Signed-off-by: sharkymcdongles <bryanfcarmichael@gmail.com>
Added configurable log format per here:
https://github.com/kedacore/keda/blob/main/BUILD.md#setting-log-levels
Fixes #144
> Expose log format setting via values

- .github/workflows/ci-core.yml
- .github/workflows/ci-http-add-on.yml
Signed-off-by: GitHub <noreply@github.com>
Improve CI for KEDA & KEDA HTTP so that:
- Workflow names & file names are aligned
- Only trigger for master pushes/PRs matching folder path
- Fix CI for KEDA HTTP
Relates to #137
Relates to https://github.com/kedacore/http-add-on/issues/104
> Improve CI for KEDA & KEDA HTTP

- keda/templates/12-keda-deployment.yaml
Signed-off-by: Jens De Temmerman <jens.dt@gmail.com>
As per https://keda.sh/docs/2.2/operate/cluster/#http-timeouts, the correct env var should be KEDA_HTTP_DEFAULT_TIMEOUT
> Corrected HTTP timeout env var

- http-add-on/templates/crd.yaml
In https://github.com/kedacore/http-add-on/pull/168, we've added fields in the CRD for `HTTPScaledObject`s to allow users to specify the target metric. This PR updates the CRD in the helm chart to add those fields.
- ~[ ] A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*~
Fixes #
> HTTP Addon: Adding CRD fields for target metric configuration

- http-add-on/README.md
- http-add-on/templates/deployment.yaml
- http-add-on/templates/rbac.yml
- http-add-on/templates/svc.yaml
- http-add-on/values.yaml
Removes the 'v' prefix from images and defaults the image tag to latest or the chart version
Fixes #150
Related to https://github.com/kedacore/http-add-on/pull/167 and https://github.com/kedacore/http-add-on/pull/125
> Default image tag and remove 'v' prefix

- .github/workflows/ci-core.yml
Signed-off-by: GitHub <noreply@github.com>
Get all cluster trigger authentication resources in CI.
Fixes #
> chore: Get all cluster trigger authentication resources in CI

- keda/templates/21-metrics-clusterrolebinding.yaml
Change cluster role binding name for metrics adapter to comply with Helm naming convention.
> Change cluster role binding name for metrics adapter

- README.md
- http-add-on/README.md
- keda/README.md
KEDA was accepted as CNCF Incubation project as per https://github.com/cncf/toc/pull/622
Relates to https://github.com/kedacore/governance/issues/2
> chore: KEDA was accepted as CNCF Incubation project

- keda/templates/22-metrics-deployment.yaml
This PR adds support to set `KEDA_HTTP_DEFAULT_TIMEOUT` in metrics-server by the same way that we are using for the operator.
I have created the PR following these steps, https://github.com/kedacore/charts/blob/master/CONTRIBUTING.md. Let me know if it's correct or I have to do/undo anything else :) 
Fixes https://github.com/kedacore/charts/issues/180
> Add support to set `KEDA_HTTP_DEFAULT_TIMEOUT` in metrics server

- keda/values.yaml
This PR adds default values in chart for resources. This default values are the [values provided in the documentation](https://keda.sh/docs/2.4/operate/cluster/#cluster-capacity-requirements)
Fixes https://github.com/kedacore/charts/issues/112
> Add resource requests/limits for KEDA deployment

- keda/templates/11-keda-clusterrolebinding.yaml
- keda/templates/21-metrics-clusterrolebinding.yaml
Signed-off-by: Xiayang Wu <xwu@rippling.com>
For https://github.com/kedacore/charts/issues/189
The rolebindings did not use the serviceAccount.name, and the helmchart will only work when setting `serviceAccount.name` same as `operator.name`, which is not always the case
Fixes #
> use .Values.serviceAccount.name for rolebinding

- CONTRIBUTING.md
This PR adds instructions to `CONTRIBUTING.md` for releasing the HTTP Addon
- ~A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)* (N/A)~
- ~README is updated with new configuration values *(if applicable)* (N/A)~
Fixes #
> Adding release instructions for the HTTP Addon

- MAINTAINERS.md
Centralize maintainer overview and point to our keda/governance repo.
- ~A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*~
- ~README is updated with new configuration values *(if applicable)*~
> docs: Centralize maintainer overview

- .github/workflows/ci-core.yml
- .github/workflows/ci-external-scaler-azure-cosmos-db.yml
- .github/workflows/ci-http-add-on.yml
Deploy Helm charts on N+5 different Kubernetes versions to ensure we are handling feature usage correctly with respect to Kubernetes versions.
> test: Deploy Helm charts on N+5 different Kubernetes versions

- http-add-on/README.md
- http-add-on/templates/deployment-interceptor.yaml
- http-add-on/templates/deployment-operator.yaml
- http-add-on/templates/deployment-scaler.yaml
- http-add-on/values.yaml
> Add nodeSelector, tolerations and affinity (http-add-on)

- keda/templates/10-keda-clusterrole.yaml
Signed-off-by: tomasspi <tom-300@hotmail.com>
Added `list` and `watch` access for service accounts to `keda-operator` cluster role.
- ~~README is updated with new configuration values *(if applicable)*~~
Relates to https://github.com/kedacore/keda/pull/2406
Relates to https://github.com/kedacore/keda/issues/2383
> fix: add list and watch access for service accounts to cluster role

- keda/Chart.yaml
- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/values.yaml
Allow to define number of replicas for Keda for HA.
> Allow define number of replicas of keda

- http-add-on/README.md
- http-add-on/templates/deployment-operator.yaml
- http-add-on/values.yaml
https://github.com/kedacore/http-add-on/pull/269 introduces the option to run the HTTP Addon system in a mode that allows one installation to work across all namespaces. This PR exposes new configuration that the change introduces
- ~A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*~
> Adding WATCH_NAMESPACE option to the HTTP Addon operator

- .github/workflows/ci-core.yml
- .github/workflows/ci-external-scaler-azure-cosmos-db.yml
- .github/workflows/ci-http-add-on.yml
Automatically deploy charts to Kubernetes v1.23
> test: Automatically deploy charts to Kubernetes v1.23

- keda/templates/01-serviceaccount.yaml
The indentation of this line is incorrect and setting a value for the service account annotations produces an invalid chart. Note that these values should be the same level as the "label" above.
Fixes #
> Fix indentation of ServiceAccount annotations

- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Currently neither the KEDA operator nor the metric server accept extra arguments in the KEDA chart. However, in some cases we may need to set additional arguments like when [How do I run KEDA with readOnlyRootFilesystem=true ? as describe in the KEDA FAQs](https://keda.sh/docs/2.5/faq/) where [metric-server flags](https://github.com/kubernetes-sigs/metrics-server/blob/master/docs/command-line-flags.txt) are needed.
This change enables the user to be able to set additional container arguments when needed.
> Add extra container args config for both keda operator and metric server

- http-add-on/templates/deployment-scaler.yaml
After https://github.com/kedacore/http-add-on/pull/386, the HTTP Addon's external scaler needs new configuration. This PR adds that new config.
Fixes #
> HTTP Addon: Adding interceptor deployment name to scaler config

- keda/README.md
- keda/templates/01-serviceaccount.yaml
- keda/values.yaml
Relates to https://github.com/kedacore/keda/issues/2487
> feat: Provide support for Azure AD Workload Identity

- keda/templates/01-serviceaccount.yaml
Relates to https://github.com/kedacore/keda/issues/2487
Relates to https://github.com/kedacore/charts/pull/263
> Fix errors in service account template.

- .github/workflows/ci-core.yml
- keda/templates/01-serviceaccount.yaml
Introduce Azure Workload Identity in CI matrix to ensure it renders correctly
Relates to https://github.com/kedacore/keda/issues/2487
Relates to https://github.com/kedacore/charts/pull/263
> chore: Introduce Azure Workload Identity in CI matrix

- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Related to https://github.com/kedacore/keda/issues/2933
> feat: use safe securityContext as default

- .github/workflows/ci-core.yml
- .github/workflows/ci-external-scaler-azure-cosmos-db.yml
- .github/workflows/ci-http-add-on.yml
Run CI against Kubernetes v1.17 -> v1.24
> ci: Run CI against Kubernetes v1.17 -> v1.24

- samples/nginx-scaledobject.yml
Signed-off-by: Swalloow <swalloow.me@gmail.com>
- Change sample scaledobject version to 2.7
- https://keda.sh/docs/2.7/scalers/cpu/
Fixes #
> fix: Change sample scaledobject version to 2.7

- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/values.yaml
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
Relates: https://github.com/kedacore/keda/issues/3066
> ability to specify timestamps in KEDA operator logs

- keda/templates/22-metrics-deployment.yaml
Remove metrics server Prometheus scrape accotations if podMonitor is enabled.
Signed-off-by: Max Howell <maxhowell24@gmail.com>
Fixes #277
> Remove metrics server Prometheus scrape accotations if podMonitor is enabled

- keda/README.md
- keda/templates/01-serviceaccount.yaml
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Added new property "automountServiceAccountToken" in ServiceAccounts and Deployments necessary for restricted environments.
Fixes #
> AutomountServiceAccountToken property implemented

- keda/README.md
- keda/templates/14-keda-podmonitor.yaml
- keda/templates/26-metrics-podmonitor.yaml
- keda/values.yaml
This MR adds support to add relabelling expressions to both Operator & Metrics Server PodMonitor.
Fixes #
> [KEDA] add relabelling support

- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Signed-off-by: Zadkiel Aharonian <hello@zadkiel.fr>
Add `upgradeStategy` field to the values that maps to the `Deployment.spec.strategy` field.
Fixes https://github.com/kedacore/charts/issues/293
> feat(keda): add deployment update strategy

- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Signed-off-by: Zadkiel Aharonian <hello@zadkiel.fr>
Add ability to specify different affinities for keda and metrics server
Fixes #
> feat(keda): affinities for keda and metrics server

- keda/templates/13-keda-poddisruptionbudget.yaml
Use v1 PodDisruptionBudget if supported (1.21+) otherwise use v1beta.
Fixes #281
> feat: add v1 PodDisruptionBudget

- .github/workflows/ci-core.yml
- keda/Chart.yaml
Remove support for Kubernetes v1.17, v1.18 & v1.19 as per [our support policy](https://github.com/kedacore/governance/blob/main/SUPPORT.md#kubernetes-support).
> chore(core): Remove support for Kubernetes v1.17, v1.18 & v1.19

- keda/README.md
- keda/values.yaml
Add/update securityContext configs:
* seccompProfile.type RuntimeDefault is needed for compliance with restricted policies in Kubernetes 1.19+
* Updated comment in metrics Deployment and README regarding readOnlyRootFilesystem
Fixes #306 
Fixes #301
> feat: add seccompProfile

- keda/Chart.yaml
- keda/README.md
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
This PR adds support for  `Pod Topology Constraints` for the `keda-operator` Pod.
Fixes #
> topology: add support for pod topology constraints to operator

- keda/README.md
Relates to https://github.com/kedacore/keda/pull/3695, https://github.com/kedacore/keda-docs/pull/945
> Remove unavailable helm flag.

- http-add-on/templates/svc-interceptor-proxy.yaml
Signed-off-by: Kostas Christidis <kchristidis@atypon.com>
- fix compatibility with Traefik to address issue https://github.com/kedacore/charts/issues/282. use `http` instead of `https` for port name.
Fixes https://github.com/kedacore/charts/issues/282
> Fix compatibility with Traefik

- .github/workflows/ci-http-add-on.yml
Signed-off-by: Jorge Turrado Ferrero <Jorge_turrado@hotmail.es>
The HTTP Add-on uses KEDA chart to install KEDA, so tested versions should match with KEDA supported versions
> Remove unsuported K8s versions from HTTP-Add-on CI

- keda/templates/22-metrics-deployment.yaml
Signed-off-by: Benjamin Berman <>
Relates to https://github.com/kedacore/keda/issues/3576
> fix: allow user to configure metrics API server port

- keda/README.md
- keda/templates/01-serviceaccount.yaml
- keda/values.yaml
Signed-off-by: Steven Jenkins De Haro 20492442+StevenJDH@users.noreply.github.com
Adds support for AWS IAM Roles for Service Accounts (IRSA) in the helm chart to the KEDA service account. For example, if `podIdentity.irsa.enabled` is set `true` along with the needed config, the below will be rendered:
```yaml
apiVersion: v1
kind: ServiceAccount
...
annotations:
eks.amazonaws.com/audience: "sts.amazonaws.com"
eks.amazonaws.com/role-arn: "arn:aws:iam::000000000000:role/example-irsa-role"
eks.amazonaws.com/sts-regional-endpoints: "true"
eks.amazonaws.com/token-expiration: "3600"
...
```
- [ X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ X] A PR …
> Added support for AWS IRSA in helm chart

- keda/README.md
The default value of the `toleration`  parameter in the documentation was incorrect.
Signed-off-by: schelv <13403863+schelv@users.noreply.github.com>
Fixes #
> default value is array instead of object

- .github/workflows/ci-core.yml
- .github/workflows/ci-external-scaler-azure-cosmos-db.yml
- .github/workflows/ci-http-add-on.yml
> fix: bump Azure/setup-helm to v3 for not using helm in alpha version

- keda/templates/01-serviceaccount.yaml
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
The `azure.workload.identity/use` label will now be required for pods as well (besides the service account).
https://github.com/Azure/azure-workload-identity/pull/629
Fixes #
> Add workload identity labels to keda pods

- .github/workflows/ci-core.yml
- keda/templates/13-keda-poddisruptionbudget.yaml
- keda/templates/25-metrics-poddisruptionbudget.yaml
As minimum k8s version for the chart is 1.23, doesn't make sense to have logic to use `policy/v1beta1` or `policy/v1`. This PR updates the versions and also modify the CI to deploy PDBs during checks to fast detect issues related with them during PRs
Fixes https://github.com/kedacore/charts/issues/325
> fix: Use correct PDB api

- keda/templates/10-keda-clusterrole.yaml
- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Restrict secret Access
Refer to Issue: https://github.com/kedacore/keda/issues/3668
PR: https://github.com/kedacore/keda/pull/3677
> Restrict secret Access

- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Support disable keep http connection alive
Relates to https://github.com/kedacore/keda/pull/3878
Relates to https://github.com/kedacore/keda/issues/3874
> Support disable keep http connection alive

- .github/workflows/ci-core.yml
- keda/templates/12-keda-deployment.yaml
This PR removes the old parameter `--metrics-port` and modifies the CI check covering the monitoring as part of the check. Also replaces the tag for CI to enforce main, in order to detect this errors faster (currently we check with latest released version, which could be outdated for testing the chart because latest release doesn't contain incoming changes)
Fixes https://github.com/kedacore/charts/issues/342
> fix(keda): Remove unknown flag when enabling prometheus on the operator

- keda/templates/12-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
Made inclusion of `.Values.additionalAnnotations` conditional
Fixes #345
> fix(core): Ensure pod annotations are applied correctly

- keda/README.md
- keda/templates/13-keda-service.yaml
- keda/templates/17-keda-servicemonitor.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/templates/23-metrics-service.yaml
- keda/templates/27-metrics-servicemonitor.yaml
- keda/values.yaml
This PR adds support for Prometheus ServiceMonitor as part of #339 and fixes the missing Prometheus scraping annotations of #354 . 
While the `metricServer` configuration is deprecated, I assume that it might be in use in some places and easier to set before migrating for some folks, so I have added the same support to it until it will be completely removed. 
Fixes #339
Fixes #354
> Adds support for Prometheus ServiceMonitor & adds missing Prometheus scraping annotations

- keda/templates/02-crd-clustertriggerauthentications.yaml
- keda/templates/03-crd-scaledjobs.keda.sh.yaml
- keda/templates/04-crd-scaledobjects.keda.sh.yaml
- keda/templates/05-crd-triggerauthentications.keda.sh.yaml
When additionalAnnotations is set - the chart is rendered with the first additional annotation on the same line with a static annotation.
> Fix additional annotation being rendered in the same line with a static annotation

- http-add-on/README.md
- http-add-on/templates/deployment-interceptor.yaml
- http-add-on/values.yaml
Use 3 replicas as minimum for interceptor to reduce blast radius in case one goes down.
More resilience tweaks will follow.
> chore(http-add-on): Use 3 replicas as minimum for interceptor

- http-add-on/templates/rbac.yml
Noticed this while trying to use the kustomize helm chart inflator
Signed-off-by: Aaron Batilo <AaronBatilo@gmail.com>
> fix: Remove duplicate key in http-addon rbac

- .github/workflows/ci-core.yml
- keda/values.yaml
Fixes https://github.com/kedacore/keda/issues/4126
> fix: ensure chart works on k8s 1.17

- keda/README.md
- keda/templates/14-keda-deployment.yaml
- keda/templates/22-metrics-deployment.yaml
- keda/values.yaml
Related to https://github.com/kedacore/keda/issues/4193
> chore: add support for configuring KEDA_HTTP_MIN_TLS_VERSION

- keda/Chart.yaml
Core Helm chart metadata is outdated.
Follow-up for #386
> fix: Core Helm chart metadata is outdated

- keda/templates/41-cert-manager-self-ca.yaml
- keda/templates/43-cert-manager-keda-tls-certificate.yaml
In some scenarios using gitops (like using ArgoCD), the current certificate spec isn't enough because minutes and seconds are missing. As the desired manifest (without min a sec) doesn't match with the live manifest (fulfilled with min and sec), ArgoCD shows an OutOfSync warning. This is skippable by config, but if the chart uses the full values, ignoring isn't needed
> chore: add minutes and seconds to cert-manager certificates

- keda/templates/30-webhooks-deployment.yaml
When [feat: add support to validating webhooks #352](https://github.com/kedacore/charts/pull/352) was merged, the documented `podLabels.webhooks`-override in the respective webhooks deployment has been missed. :slightly_smiling_face:
> fix(keda): Allow for podLabels override in the webhooks deployment

- keda/templates/22-metrics-deployment.yaml
Fix extraVolumes and extraVolumeMounts indentation in 22-metrics-deployment.yaml
Fixes #410
> Fix extraVolumes and extraVolumeMounts indentation

- keda/values.yaml
Thanks to the cert-management, KEDA mestrics server always receives the certificates as a mounted path, so we can set `readOnlyRootFilesystem: true` as default
Related to https://github.com/kedacore/charts/issues/410
> chore: enable `readOnlyRootFilesystem: true` for metrics server

- .github/workflows/ci-http-add-on.yml
For 1.23 clusters, the workflow now installs the 2.8.x chart, which is the latest chart compatible with 1.23.  All other cluster versions install the chart from the checked out code.
Fixes #422
> ci: http add on workflow now installs appropriate kedacore/keda chart for 1.23 clusters

- http-add-on/Chart.yaml
- http-add-on/README.md
- http-add-on/values.yaml
This resolves issues #420 by adding default resource limits/requests
- n/a
Fixes #420
> Add resource limits and requests for the interceptor pod component

- http-add-on/templates/deployment-operator.yaml
The kube-rbac-proxy container in the operator deployment is missing the `resources` template. In environments where limits are required to be set on all deployments, this causes manual labor for k8s developers. 
I would update the README to reflect this change, however, the README is already essentially wrong. 
for example [The http-add-on README](https://github.com/kedacore/charts/blob/main/http-add-on/README.md#L138)
states that there is a configuration for `interceptor.resources.limits.cpu`, while in the deployment template it uses a top level resource declaration `{{- toYaml .Values.resources | nindent 12 }}`. I could instead close this MR and create another one to instead fix the templates to reflect the README.
> Add resource template to kube-rbac-proxy container in http-add-on helm chart

- keda/templates/17-keda-servicemonitor.yaml
- keda/templates/27-metrics-servicemonitor.yaml
Add `honorLabels: true` to `ServiceMonitor` of both keda metrics server and keda operator to preserve original namespace labels
Fixes #434
> Add honorLabels to keda operator and metricsserver ServiceMonitor

- keda/README.md
- keda/templates/manager/clusterrole.yaml
- keda/values.yaml
this change adds ClusterRoles to aggregate rbac for
clustertriggerauthentications, scaledjobs, scaledobjects and
triggerauthentications to the kubernetes default roles view, edit and
admin via aggregation.
These ClusterRoles are optional and disabled by default. Set
rbac.aggregateToDefaultRoles to enable.
Signed-off-by: Till Adam <lxmail@web.de>
Fixes #256
> aggregate rbac for crds to default roles

- http-add-on/README.md
- http-add-on/templates/rbac-aggregateclusterroles.yaml
- http-add-on/values.yaml
This change is similar to https://github.com/kedacore/charts/pull/257.  It adds the AggregateToDefaultRoles to the http addon.  These ClusterRoles are optional and disabled by default. Set rbac.aggregateToDefaultRoles to enable.
Signed-off-by: Chris Reiche creiche@gmail.com
Fixes #
> Add aggregateToDefaultRules to http add-on

- keda/README.md
We should keep an option to disable admission webhooks.
> chore: Amission webhooks won't be mandatory in v2.12

- keda/templates/manager/podmonitor.yaml
- keda/templates/manager/servicemonitor.yaml
- keda/templates/metrics-server/podmonitor.yaml
- keda/templates/metrics-server/servicemonitor.yaml
Remove a `honorLabels` field from the manager's service monitor due to changes in the keda-dashboard.json
Related PR: https://github.com/kedacore/keda/pull/4539
> remove honor label from manager service monitor

- keda/README.md
- keda/templates/manager/service.yaml
- keda/templates/metrics-server/deployment.yaml
- keda/templates/metrics-server/podmonitor.yaml
- keda/templates/metrics-server/service.yaml
- keda/templates/metrics-server/servicemonitor.yaml
- keda/values.yaml
Related to https://github.com/kedacore/keda/issues/3930
> Remove deprecated prometheus metrics from MS

- keda/Notes.txt
- keda/templates/manager/servicemonitor.yaml
- keda/templates/webhooks/servicemonitor.yaml
Improve deprecation for service monitor relabelings and fix earlier copy/paste mistake.
Relates to https://github.com/kedacore/charts/issues/457
> chore: Improve deprecation for service monitor relabelings

- http-add-on/.helmignore
- http-add-on/README.md
- http-add-on/README.md.gotmpl
- http-add-on/values.yaml
Implements the same from PR #446 for the http-add-on.
Related to:
- #444
> docs(http-add-on): Introduce helm-docs for documentation

- .github/PULL_REQUEST_TEMPLATE.md
- keda/README.md
- keda/README.md.gotmpl
- keda/values.yaml
This is a follow-up of PR #446.
- move `serviceAccount.xyz` to general section
- rebase issue related to feature `extraObjects`
- Add link to usage description to PR template
> docs(keda): Fix some helm-docs issues

- .github/workflows/ci-core.yml
Automatically deploy KEDA Core to Kubernetes v1.27
> ci: Automatically deploy KEDA Core to Kubernetes v1.27

- keda/templates/webhooks/deployment.yaml
- keda/templates/webhooks/service.yaml
- keda/values.yaml
Fixes #468
Need this change : https://github.com/kedacore/keda/pull/4712
> feat: Allow to change port for Webhooks and add hostnetwork

- CONTRIBUTING.md
- http-add-on/README.md.gotmpl
- keda/README.md
- keda/README.md.gotmpl
Add re-generation of Helm docs to release
> chore: Add re-generation of Helm docs to release

- .github/workflows/ci-core.yml
- keda/templates/manager/service.yaml
- keda/templates/metrics-server/service.yaml
- keda/templates/serviceaccount.yaml
- keda/templates/webhooks/service.yaml
Annotations are optional but enforced
- `additionalAnnotations` are optional but enforced
- `additionalAnnotations` & `service.additionalAnnotations` are not rendered correctly wrt whitespace
- `toYaml` drops quoting
- `additionalAnnotations` & `service.additionalAnnotations` was not supported in webhooks
- CI did not use these annotations during tests
Fixes #481
> fix(core): Annotations are not handled correctly

- keda/templates/NOTES.txt
- keda/values.yaml
Improve Helm notes a bit to make it more end-user friendly and add missing ASCII art:
```
:::^.     .::::^:     :::::::::::::::    .:::::::::.                   .^.
7???~   .^7????~.     7??????????????.   :?????????77!^.              .7?7.
7???~  ^7???7~.       ~!!!!!!!!!!!!!!.   :????!!!!7????7~.           .7???7.
7???~^7????~.                            :????:    :~7???7.         :7?????7.
7???7????!.           ::::::::::::.      :????:      .7???!        :7??77???7.
7????????7:           7???????????~      :????:       :????:      :???7?5????7.
7????!~????^          !77777777777^      :????:       :????:     ^???7?#P7????7.
7???~  ^????~                            :????:      :7???!     ^???7J#@J7?????7.
7???~   :7???!.                          :????:   .:~7???!. …
```
> fix(core): Add missing ASCII art

- keda/templates/cert-manager/keda-issuer.yaml
- keda/templates/cert-manager/self-issuer.yaml
- keda/templates/manager/clusterrole.yaml
- keda/templates/manager/clusterrolebinding.yaml
- keda/templates/manager/deployment.yaml
- keda/templates/manager/poddisruptionbudget.yaml
- keda/templates/manager/podmonitor.yaml
- keda/templates/manager/prometheusrules.yaml
- keda/templates/manager/role.yaml
- keda/templates/manager/rolebinding.yaml
- keda/templates/manager/service.yaml
- keda/templates/manager/servicemonitor.yaml
- keda/templates/metrics-server/apiservice.yaml
- keda/templates/metrics-server/clusterrole.yaml
- keda/templates/metrics-server/clusterrolebinding.yaml
- keda/templates/metrics-server/deployment.yaml
- keda/templates/metrics-server/poddisruptionbudget.yaml
- keda/templates/metrics-server/podmonitor.yaml
- keda/templates/metrics-server/service.yaml
- keda/templates/metrics-server/servicemonitor.yaml
- keda/templates/webhooks/deployment.yaml
- keda/templates/webhooks/poddisruptionbudget.yaml
- keda/templates/webhooks/prometheusrules.yaml
- keda/templates/webhooks/service.yaml
- keda/templates/webhooks/servicemonitor.yaml
- keda/templates/webhooks/validatingconfiguration.yaml
When using the keda chart, I noticed that annotations can generate empty key's when no additional annotations are passed in e.g.
```
apiVersion: v1
kind: Service
metadata:
annotations:
labels:
app.kubernetes.io/name: keda-operator    
helm.sh/chart: keda-2.11.0
app.kubernetes.io/component: operator
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/instance: release-name
app.kubernetes.io/part-of: keda-operator
app.kubernetes.io/version: 2.11.0
name: keda-operator
namespace: default
spec:
ports:
- name: metricsservice
port: 9666
targetPort: 9666
selector:
app: keda-operator
---
```
I am attempted to just alter the helm template logic to only create the annotation key should there be a value passed in. I have added a before and after yaml from running `helm template` locally. I carried …
> Updating templates to remove blank annotations

- keda/templates/metrics-server/deployment.yaml
#488 investigation, looks like this may have been missed as part of [this](https://github.com/kedacore/charts/pull/432/files#diff-cef26632adc4078d60a55b5799578907d1f409eb9f2cfd1910b4974ebc87185dL43) - [this](https://github.com/kubernetes-sigs/metrics-server/blob/master/docs/command-line-flags.txt) I think its safe to remove that extra field. 
Fixes #
#488
> Removing MS-apiserver MS path

- keda/templates/webhooks/deployment.yaml
Webhooks prometheus port already has a default value, so doesn't make sense to check if it's enabled or not to override the value, considering that it doesn't disable the server (which would need to set 0 instead of the default value)
Related to https://github.com/kedacore/keda/issues/4777
> fix(keda): Remove unnecesary condition for setting prometheus port in webhooks

- http-add-on/templates/crd.yaml
- http-add-on/templates/rbac-interceptor.yml
- http-add-on/templates/rbac-operator.yml
- http-add-on/templates/rbac-scaler.yml
- keda/templates/manager/clusterrole.yaml
- keda/templates/manager/role.yaml
- keda/templates/metrics-server/clusterrole.yaml
The field `creationTimestamp` is auto-generated by kubernetes. This field is ignored during creation/update because it's non-editable by clients.
> chore: Remove all non-editable keys from resources

- keda/templates/webhooks/validatingconfiguration.yaml
Remove unnecessary `namespace` from metadata since ValidatingWebhookConfiguration is a cluster scoped resource.
Fixes #
> remove namespace from webhook

- keda/templates/metrics-server/apiservice.yaml
After adding cert-management and removing `insecureSkipTLSVerify`, it seems that during migration from the newer versions, helm doesn't remove the old value (probably because the apiservice doesn't set it explicitly).
To prevent this error, this PR explicitly sets the `insecureSkipTLSVerify: false`. This property can be removed in future versions once enough time has passed since we changed the value.
> fix: explicitly set insecureSkipTLSVerify as disabled for upgrades

- keda/README.md
- keda/templates/manager/deployment.yaml
- keda/templates/metrics-server/deployment.yaml
- keda/templates/webhooks/deployment.yaml
- keda/values.yaml
Hi team,
This PR allows user to set custom value for livenessProbe and readinessProbe too
Fixes https://github.com/kedacore/charts/issues/508
> Allow user to set custom `livenessProbe` and `readinessProbe`

- keda/README.md
- keda/templates/manager/deployment.yaml
- keda/templates/metrics-server/deployment.yaml
- keda/templates/webhooks/deployment.yaml
- keda/values.yaml
> update deployment with revision history limit

- keda/templates/crds/crd-clustertriggerauthentications.yaml
- keda/templates/crds/crd-triggerauthentications.yaml
Update helm chart with crd needed forwith https://github.com/kedacore/keda/issues/5067
- [N/A] README is updated with new configuration values *(if applicable)* [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#documentation)
Fixes https://github.com/kedacore/keda/issues/5067
> feat: update crd to allow vault secret to handle write operation

- keda/templates/webhooks/service.yaml
This addresses the issue https://github.com/kedacore/charts/issues/500
Only webhook's svc name is `http`, others are fine
Fixes #
> Fix the svc name of webhook to avoid breaking istio

- keda/README.md
- keda/templates/metrics-server/deployment.yaml
- keda/values.yaml
Signed-off-by: Adarsh-verma-14 [t_adarsh.verma@india.nec.com](mailto:t_adarsh.verma@india.nec.com)
Add one deployment arg in keda-metrics-apiserver for show only log messages with a severity level of ERROR or higher in the stderr
> Show only logs with a severity level of ERROR or higher in the stderr

- keda/README.md
- keda/README.md.gotmpl
- keda/templates/manager/deployment.yaml
- keda/templates/manager/service.yaml
- keda/templates/metrics-server/deployment.yaml
- keda/templates/metrics-server/service.yaml
- keda/templates/webhooks/deployment.yaml
- keda/templates/webhooks/service.yaml
- keda/values.yaml
> Support profiling for keda components

- keda/templates/webhooks/validatingconfiguration.yaml
Related to https://github.com/kedacore/keda/pull/4696 
Added missing configuration for validation webhook (TriggerAuthentication)
Relates to https://github.com/kedacore/keda/issues/5109
> Fix TriggerAuthentication - added configuration for validation webhook

- CONTRIBUTING.md
Clarify that contributors do not have to ship Helm chart which comes up a lot.
> docs: Clarify that contributors do not have to ship Helm chart

- keda/templates/manager/deployment.yaml
- keda/templates/metrics-server/deployment.yaml
- keda/values.yaml
Signed-off-by: Adarsh-verma-14 [t_adarsh.verma@india.nec.com](mailto:t_adarsh.verma@india.nec.com)
Add  disable-compression arg for both operator and metrics-server.
> add  disable-compression arg for both operator and metrics-server

- docs/index.yaml
- keda/README.md
During last release, we removed http add-on 0.6.0 from the index by mistake
Fixes https://github.com/kedacore/charts/issues/578
> fix: restore http-add-on chart 0.6.0 indexing

- http-add-on/README.md
- http-add-on/templates/operator/deployment.yaml
- http-add-on/values.yaml
The http-add-on helm chart has been updated so the `operator` component's deployment uses the `resources` specified in the helm chart values, and allows them to be overwritten.
- ~README is updated with new configuration values *(if applicable)* [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#documentation)~
- ~A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*~
Fixes #
https://github.com/kedacore/charts/issues/565
> Fix http-add-on operator resources

- http-add-on/README.md
- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/templates/operator/deployment.yaml
- http-add-on/templates/scaler/deployment.yaml
- http-add-on/values.yaml
`http-add-on`:
- Added logging related configuration arguments to deployments and values file
- Updated README with `helm-docs`
- ~A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*~
Fixes #
https://github.com/kedacore/charts/issues/566
> Fix http-add-on verbosity configuration

- keda/templates/manager/clusterrole.yaml
Allow keda-operator to access the LimitRange resources in the cluster. The operator requires this to validate whether the default limits are available on the container in case of using CPU/memory triggers.
This is to sync the chart with changes in https://github.com/kedacore/keda/pull/5377
Relates to https://github.com/kedacore/keda/issues/5348
> feat(ClusterRole): Add RBAC rule to allow access to `LimitRange`

- keda/templates/metrics-server/apiservice.yaml
As mentioned [here](https://github.com/kedacore/keda/issues/4732) and discussed [here](https://github.com/kedacore/keda/discussions/5123) the setting of `insecureSkipTLSVerify` in apiservice.apiregistration.k8s.io will disturb CI/CD pipelines like ArgoCD or, just in our case, Fleet. The adding of `caBundle` will remove `insecureSkipTLSVerify` automatically in the cluster. Fleet will state in "modified" instead of "active". Removing this field in Helm solves the issue.
Fixes https://github.com/kedacore/keda/issues/4732
hint: Helm has also this [genCa](https://helm.sh/docs/chart_template_guide/function_list/#genca) function to generate certificate
> remove not required insecureSkipTLSVerify

- keda/templates/webhooks/deployment.yaml
Align deployment for extraVolumes and extraVolumesMount for fix problem Error: YAML parse error on keda/templates/webhooks/deployment.yaml: error converting YAML to JSON: yaml: line 96: did not find expected key
Aligned deployment.yml extraVolumes and extraVolumesMount of templates/webhooks to others deployment template 
Fixes #589
> Update templates/webhooks deployment

- keda/templates/_helpers.tpl
- keda/templates/crds/crd-clustertriggerauthentications.yaml
- keda/templates/crds/crd-scaledjobs.yaml
- keda/templates/crds/crd-scaledobjects.yaml
- keda/templates/crds/crd-triggerauthentications.yaml
When deploying keda with argocd, changing the releasename keep causes a warning in the argocd application. for example,   argocd appplication name is keda-test and releaseName: keda, keep causes a warning
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: keda-test
namespace: argocd
spec:
source:
helm:
releaseName: keda
```
[Argocd offical document](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-release-name) say that 
`Please note that overriding the Helm release name might cause problems when the chart you are deploying is using the app.kubernetes.io/instance.
`
And, I use [argo rollout helm charts](https://github.com/argoproj/argo-helm/blob/main/charts/argo-rollouts/templates/crds/rollout-crd.yaml#L14), [karpenter helm …
> Fix Remove app.kubernetes.io/instance label in crd

- keda/README.md
- keda/templates/manager/ciliumnetworkpolicy.yaml
- keda/templates/metrics-server/ciliumnetworkpolicy.yaml
- keda/templates/webhooks/ciliumnetworkpolicy.yaml
- keda/values.yaml
add cilium network policies support
> Add ciliumnetworkpolicies

- keda/README.md
- keda/templates/manager/servicemonitor.yaml
- keda/templates/metrics-server/servicemonitor.yaml
- keda/templates/webhooks/servicemonitor.yaml
- keda/values.yaml
After breaking [this PR](https://github.com/kedacore/charts/pull/539) trying to fix the conflicts, I open this PR with the OP's changes (all the KUDOS to @guicholeo)
> Add tlsConfig for ServiceMonitor

- keda/templates/manager/podmonitor.yaml
PodMonitor port name is set as `http` but the deployment port name is set as `metrics`.
Fixes #601
> fix: pod monitor port name does not match deployment spec

- keda/README.md
- keda/templates/manager/podmonitor.yaml
- keda/templates/manager/servicemonitor.yaml
- keda/templates/metrics-server/podmonitor.yaml
- keda/templates/metrics-server/servicemonitor.yaml
- keda/templates/webhooks/servicemonitor.yaml
- keda/values.yaml
Add support for metricRelabelings to Pod and Service monitors.
Ref: https://www.robustperception.io/relabel_configs-vs-metric_relabel_configs/ 
Fixes #514
> feat: Add support for metricRelabelings to Pod and Service monitors

- keda/README.md
- keda/templates/manager/ciliumnetworkpolicy.yaml
- keda/values.yaml
This PR adds support to be able to add extra egress rules to the ciliumnetworkpolicy if for instance, the prometheus used to scale is outside the cluster as the current ciliumnetworkpolicy only allows egress to the cluster pods and the api-server
> Allow extra egress rules for the keda operator ciliumnetworkpolicy

- keda/README.md
- keda/values.yaml
I removed the comment about cert-issuer by error because it wasn't in values.yaml during [this PR](https://github.com/kedacore/charts/pull/610)
> chore: Add missing comment to values.yaml

- .github/workflows/ci-core.yml
- keda/README.md
- keda/templates/manager/deployment.yaml
- keda/values.yaml
Add configuration parameters for specifying extra sidecar containers and extra init containers. Implements #607 
Fixes #
> Add extra sidecar containers config for Keda operator

- keda/templates/crds/crd-clustertriggerauthentications.yaml
- keda/templates/crds/crd-triggerauthentications.yaml
identity provider: "none" is officially supported and allowed value based on the docs and keda golang structs:
https://github.com/kedacore/keda/blob/main/apis/keda/v1alpha1/triggerauthentication_types.go#L123
```
const (
PodIdentityProviderNone          PodIdentityProvider = "none"
PodIdentityProviderAzure         PodIdentityProvider = "azure"
PodIdentityProviderAzureWorkload PodIdentityProvider = "azure-workload"
PodIdentityProviderGCP           PodIdentityProvider = "gcp"
PodIdentityProviderAwsEKS        PodIdentityProvider = "aws-eks"
PodIdentityProviderAwsKiam       PodIdentityProvider = "aws-kiam"
PodIdentityProviderAws           PodIdentityProvider = "aws"
)
```
and in the docs:
https://keda.sh/docs/2.13/concepts/authentication/
```
apiVersion: keda.sh/v1alpha1
kind: …
```
> fix: add "none" as identity provider

- http-add-on/templates/_helpers.tpl
- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/templates/interceptor/service-admin.yaml
- http-add-on/templates/interceptor/service-proxy.yaml
- http-add-on/templates/operator/deployment.yaml
- http-add-on/templates/operator/service.yaml
- http-add-on/templates/scaler/deployment.yaml
- http-add-on/templates/scaler/service.yaml
`matchLabels` in the HTTP Add-on are wrong because they include version information but `matchLabels` is inmutable, so the upgrades are blocked due to this. The PR adjust the `matchLabels` to just the only ones which doesn't change across the versions.
Fixes https://github.com/kedacore/http-add-on/issues/656
> fix(add-on): Allow upgrades removing version labels from selectors

- keda/values.yaml
update the value for admission webhooks pod .
Fixes #616
> correct the value for admission webhooks pod

- keda/templates/crds/crd-clustertriggerauthentications.yaml
- keda/templates/crds/crd-triggerauthentications.yaml
- keda/templates/manager/deployment.yaml
- keda/templates/metrics-server/deployment.yaml
- keda/values.yaml
Related https://github.com/kedacore/keda/pull/5782
> chore: Remove deprecated AAD-Pod-Identity and AWS-KIAM auths

- keda/README.md
- keda/templates/manager/deployment.yaml
- keda/values.yaml
https://github.com/kedacore/keda/pull/5859
Fixes https://github.com/kedacore/keda/issues/5860
> Allow CA dirs to be specified beyond /custom/ca/

- keda/templates/crds/crd-cloudeventsources.yaml
Use the same labels for all CRDs.
> fix: labels on cloudeventsources CRD should be the same as other CRDs

- keda/templates/manager/deployment.yaml
- keda/values.yaml
the cmd arg does not exist for older KEDAs
This way the default value is still correctly [applied](https://github.com/kedacore/keda/pull/5859/files#diff-891ba2cfffd82a8ae4131c88beb092d2a88149f579c931e3a1f7ca77fbfc82a5R110) for new keda version because they have the fallback implemented also in the golang code
cc @zroubalik
> Comment out new option in helm values, because it breaks the old versions of keda

- http-add-on/README.md
- http-add-on/templates/operator/deployment.yaml
- http-add-on/templates/operator/rbac.yml
- http-add-on/templates/operator/service.yaml
- http-add-on/templates/operator/serviceaccount.yaml
- http-add-on/values.yaml
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
This also skips creation of the HTTP Operator Deployment, Service, ServiceAccount and RBAC if desired number of replicas is < 1
> http-add-on: ability to specify number of operator replicas

- keda/README.md
- keda/values.yaml
It updates the `values.yaml` file to correctly separate the `registry` and `repository` values for the KEDA image.
Changes Made:
- Set the default value of `image.keda.registry` to `ghcr.io`.
- Adjusted `image.keda.repository` to `kedacore/keda`.
> Correct default registry value in values.yaml

- keda/templates/manager/deployment.yaml
- keda/templates/manager/serviceaccount.yaml
- keda/templates/metrics-server/deployment.yaml
- keda/templates/metrics-server/serviceaccount.yaml
- keda/templates/webhooks/deployment.yaml
- keda/templates/webhooks/serviceaccount.yaml
Fixes following issue:
When setting (for example) (.Values.serviceAccount.operator).automountServiceAccountToken to boolean false, the "| default" part kicks in.
Fix is strongly inspired from https://github.com/helm/helm/issues/12080#issuecomment-1555147255
> fix: broken "| default" logic for automountServiceAccountToken

- keda/templates/crds/crd-cloudeventsources.yaml
Add forgotten block to template crds.additionalAnnotations into crd-cloudeventsources.yaml annotations.
> fix: add forgotten crds.additionalAnnotations to crd-cloudeventsources.yaml

- .github/workflows/ci-core.yml
- keda/templates/crds/crd-clustercloudeventsources.yaml
- keda/templates/manager/clusterrole.yaml
Introduce ClusterCloudEventSource
Fixes # https://github.com/kedacore/keda/pull/5816
> Introduce ClusterCloudEventSource

- http-add-on/templates/interceptor/poddisruptionbudget.yaml
- http-add-on/values.yaml
There is no pod disruption budget on the http addon interceptors, which
means that during node rollover, there might not be any interceptors
available to add requests to its queue. Since the queues themselves are
in memory, that means that there would be dropped requests.
Closes #658
> Add a pdb template for the http-add-on interceptor

- keda/templates/metrics-server/service.yaml
- keda/templates/webhooks/service.yaml
Despite Istio docs stating that setting the name of the port to https should result in the protocol being https (TLS not intercepted), it doesn't appear to work for us, and only works by explicitly setting appProtocol.
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection
Fixes #
> istio compatibility with appProtocol: https

- http-add-on/README.md
- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/values.yaml
> add topology spread constraints to interceptor

- keda/templates/manager/minimal-rbac.yaml
This is a followup to: https://github.com/kedacore/charts/pull/643
Technically this PR is not necessary because the `keda-operator` uses an informer cache and `GET` requests are handled internally (the cache is formed by `LIST` and then `WATCH`), but this is to remain consistent with the documentation where all three `LIST`, `WATCH` and `GET` are explicitly mentioned.
https://keda.sh/docs/2.15/operate/cluster/#restrict-secret-access
Worthy to mention adding `GET` along `LIST` doesn't elevate any permissions. It's an implementation detail of the RBAC in kube-apiserver.
Relates to: https://github.com/kedacore/charts/issues/685
> Add Secret GET to keda-operator minimal RBAC

- http-add-on/templates/crd.yaml
- http-add-on/templates/interceptor/rbac.yml
1. add RBAC for watching `Services`
2. HTTPScaledObject supports referencing port as `portName` to follow common conventions in k8s API
see also: https://github.com/kedacore/http-add-on/pull/1174
> http-add-on: support portName on HTTPScaledObject

- .github/workflows/ci-core.yml
I've also replaced kube-prometheus-stack with just prometheus-crds because it's lighter and solves the errors deploying Prometheus
Fixes #
> chore: Bump k8s versions used for unit tests

- keda/templates/metrics-server/clusterrolebinding.yaml
Sadly both metrics-server and HPA namespaces were updated in the previous MR where I added an option to use custom metrics-server namespace, this should be partially reverted since it should be required only for RoleBinding of metrics-server, not ClusterRoleBinding of HPA.
Fixes #
- Removed .Values.rbac.controlPlaneServiceAccountsNamespace variable binding for HPA ClusterRoleBinding
> Reverting setting HPA namespace variable

- keda/templates/manager/service.yaml
- keda/templates/metrics-server/service.yaml
- keda/templates/webhooks/service.yaml
- keda/values.yaml
Adds `appProtocol` to the services collecting metrics using mTLS https://github.com/prometheus/prometheus/issues/10213#issuecomment-1064280828
Fixes #
> Add appProtocol to services collecting metrics using mTLS

- keda/templates/cert-manager/self-ca.yaml
The renewBefore value for the root ca was simply too low barely giving the leaf certificate any time to renew itself. This leads to the root ca expiring before the leaf certificates expires.
By removing the renewBefore values we go back to the 2/3 default and as long as the leaf certificate is only valid for half of the root it should be fine.
Fixes #710
> fix(cert-manager): Ensure there is at least one leaf certificate renewal when renewing the CA

- keda/templates/manager/deployment.yaml
- keda/values.yaml
> add: helm values for --enable-webhook-patching flag

- keda/templates/manager/minimal-rbac.yaml
Add r/w permissions for cloudeventsources and clustercloudeventsources in the minimal-rbac ClusterRole template.
These are required to prevent a crashloop when shipping the operator with the `watchNamespace` property.
Fixes kedacore/keda#6084
> fix(rbac): add missing eventing.keda.sh permissions

- keda/templates/webhooks/validatingconfiguration.yaml
- keda/values.yaml
Adds timeout to admission webhooks
Fixes #
> Add webhook timeouts

- keda/templates/manager/deployment.yaml
- keda/templates/metrics-server/deployment.yaml
- keda/templates/webhooks/deployment.yaml
- keda/values.yaml
> feat: support disabling docker legacy service links creation in keda containers

- keda/templates/crds/crd-clustercloudeventsources.yaml
Similar to https://github.com/kedacore/charts/pull/668
Add forgotten block to template crds.additionalAnnotations into crd-clustercloudeventsources.yaml annotations.
>  fix: add forgotten crds.additionalAnnotations to crd-clustercloudeventsources.yaml

- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/templates/operator/deployment.yaml
- http-add-on/templates/scaler/deployment.yaml
- http-add-on/values.yaml
This setting is already present in KEDA operator.
> HTTP Add-On: add `stackTracesEnabled` logging option

- http-add-on/README.md
- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/templates/operator/deployment.yaml
- http-add-on/templates/scaler/deployment.yaml
- http-add-on/values.yaml
This PR extends the helm chart for the http-add-on to set pod annotations.
> HTTP-ADD-ON: add pod annotations

- keda/README.md
- keda/templates/crds/crd-clustertriggerauthentications.yaml
- keda/templates/crds/crd-triggerauthentications.yaml
- keda/templates/manager/clusterrole.yaml
- keda/values.yaml
Updates CRDs to support `BoundServiceAccountToken` trigger auth provider/source. Also adds a helm value of type array called `serviceAccountTokenCreationRoles` which allows you to add objects of `name` and `namespace` corresponding to service accounts in the cluster that you'd like the `keda-operator` to be able to request service account tokens from. 
Related to https://github.com/kedacore/keda/pull/6272
> feat: support `BoundServiceAccountToken` triggerAuth provider

- keda/README.md
- keda/templates/metrics-server/deployment.yaml
- keda/values.yaml
This PR adds support for configuring DNS settings specifically for the KEDA metrics server pod through the new `metricsServer.dnsConfig` parameter in `values.yaml`.
```yaml
metricsServer:
dnsConfig:
nameservers:
- "8.8.8.8"
- "1.1.1.1"
searches:
- "metrics.example.com"
options:
- name: "ndots"
value: "3"
```
> feat(metrics-server): add `dnsConfig` support

- http-add-on/templates/interceptor/rbac.yml
- http-add-on/templates/scaler/rbac.yml
see also: https://github.com/kedacore/http-add-on/pull/1298
see also: https://github.com/kedacore/http-add-on/issues/1297
> http-add-on: migrate v1.Endpoints to discoveryv1.EndpointSlices

- .github/workflows/ci-core.yml
- .github/workflows/ci-http-add-on.yml
Let's align with 2.18 compatibility
Relates: https://github.com/kedacore/keda/issues/6853
> chore: update Kubernetes versions in CI workflows for compatibility
